### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by 7ooL** [DragonTech26/BDSAddonManager#13]
I run a dedicated bedrock server on a Linux server, is there a way to get this working for it?

**Comment by DragonTech26** [comment]
On my server (which is also on Linux), I have the world files available on an SMB share, which I can then access through the software. 

Unfortunately, the software itself is not currently available for Linux, so it needs to be run on a Windows machine or through WINE.

**Comment by 7ooL** [comment]
I must be incorrectly assuming it manages the add ons while the server is running. I was looking for a way to disable addons running on my server which I access through the Xbox console. The server side addons don't appear to be toggle-able on the Xbox, when enabled on the server they are always enabled it appears. I was hoping to not need a server restart for changing an addon.

**Comment by DragonTech26** [comment]
That is correct. The server needs to be restarted to apply the changes. Minecraft doesn't allow the client to edit addons that are running on the server, or add or remove addons while it's running. Everything needs to be done on the host machine, as inconvenient as that can be.
